
#mybatis:
#    config-location: classpath:mybatis-config.xml

spring:
    profiles:
        active: dev
    datasource:
        username: sq
        password:
        driver-class-name: org.h2.Driver
        initialize: false

---

spring:
    profiles: dev
    datasource:
        url: jdbc:h2:~/db/journal/journal

---

spring:
    profiles: test
    datasource:
        url: jdbc:h2:mem:testdb